# Generated by Django 5.2.11 on 2026-02-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_courtesy',
            field=models.BooleanField(default=False, help_text='Grant Pro status without Stripe subscription'),
        ),
    ]
