# Generated by Django 5.2.11 on 2026-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_querycache_queryprompt_searchhistory_top_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf_directory',
            field=models.CharField(blank=True, default='', help_text='Local directory path containing building code PDFs', max_length=500),
        ),
    ]
