# Generated by Django 5.2.9 on 2026-03-08 13:34

from django.db import migrations, models


def copy_bbox_bounds(apps, schema_editor):
    CodeMapNode = apps.get_model("core", "CodeMapNode")
    for node in CodeMapNode.objects.exclude(bbox__isnull=True).iterator(chunk_size=500):
        bbox = node.bbox or {}
        if node.initial_page_top is None and bbox.get("t") is not None:
            node.initial_page_top = bbox.get("t")
        if node.final_page_bottom is None and bbox.get("b") is not None:
            node.final_page_bottom = bbox.get("b")
        node.save(update_fields=["initial_page_top", "final_page_bottom"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_user_pdf_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="codemapnode",
            name="final_page_bottom",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="codemapnode",
            name="initial_page_top",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(copy_bbox_bounds, noop_reverse),
        migrations.RemoveField(
            model_name="codemapnode",
            name="bbox",
        ),
    ]
