# Generated by Django 5.2.11 on 2026-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_codemapnode_bbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemapnode',
            name='provision_transitions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
