# Generated by Django 5.2.11 on 2026-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_codemapnode_provision_transitions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='codemapnode',
            name='code_map_node_unique',
        ),
        migrations.AddField(
            model_name='codemapnode',
            name='division',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='codemapnode',
            constraint=models.UniqueConstraint(fields=('code_map', 'node_id', 'division'), name='code_map_node_unique'),
        ),
    ]
