# Generated by Django 5.2.11 on 2026-05-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_meta_amendment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordIDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_code', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('doc_count', models.IntegerField()),
                ('total_docs', models.IntegerField()),
                ('idf', models.FloatField()),
            ],
            options={
                'db_table': 'keyword_idf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodeEditionProvisionVersionClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'code_edition_provision_version_clauses',
                'ordering': ['apply_order'],
            },
        ),
        migrations.CreateModel(
            name='RegulationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('original_url', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'regulation_assets',
            },
        ),
        migrations.RemoveIndex(
            model_name='codeeditionprovisionversion',
            name='code_editio_clause__f4a7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='codeeditionprovision',
            new_name='code_editio_edition_50917e_idx',
            old_name='code_editio_edition_a2b4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='codeeditionprovision',
            new_name='code_editio_parent__bb75bc_idx',
            old_name='code_editio_parent__d1e5f2_idx',
        ),
        migrations.RenameIndex(
            model_name='codeeditionprovisionversion',
            new_name='code_editio_provisi_4c0611_idx',
            old_name='code_editio_provisi_c3d6e7_idx',
        ),
        migrations.RenameIndex(
            model_name='codeeditionprovisionversion',
            new_name='code_editio_effecti_5aaac6_idx',
            old_name='code_editio_effecti_a5b8c9_idx',
        ),
        migrations.RenameIndex(
            model_name='regulation',
            new_name='regulations_edition_541927_idx',
            old_name='regulations_edition__c7e8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='regulationclause',
            new_name='regulation__regulat_569b65_idx',
            old_name='regulation_c_regulat_b3e1a2_idx',
        ),
        migrations.RenameIndex(
            model_name='regulationclause',
            new_name='regulation__target__e9fb7f_idx',
            old_name='regulation_c_target__a9f3b1_idx',
        ),
        migrations.RemoveField(
            model_name='codeeditionprovisionversion',
            name='action',
        ),
        migrations.RemoveField(
            model_name='codeeditionprovisionversion',
            name='clause',
        ),
        migrations.AlterField(
            model_name='codeeditionprovision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codeeditionprovisionversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provisionmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provisionversiontable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regulationclause',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='codeeditionprovisionversionclause',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regulationclause'),
        ),
        migrations.AddField(
            model_name='codeeditionprovisionversionclause',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codeeditionprovisionversion'),
        ),
        migrations.AddField(
            model_name='codeeditionprovisionversion',
            name='contributing_clauses',
            field=models.ManyToManyField(blank=True, related_name='contributed_to_versions', through='core.CodeEditionProvisionVersionClause', to='core.regulationclause'),
        ),
        migrations.AddField(
            model_name='regulationasset',
            name='regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.regulation'),
        ),
        migrations.AddIndex(
            model_name='codeeditionprovisionversionclause',
            index=models.Index(fields=['clause'], name='code_editio_clause__47a4d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='codeeditionprovisionversionclause',
            constraint=models.UniqueConstraint(fields=('version', 'clause'), name='version_clause_unique'),
        ),
        migrations.AddIndex(
            model_name='regulationasset',
            index=models.Index(fields=['path'], name='regulation__path_a16451_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulationasset',
            constraint=models.UniqueConstraint(fields=('regulation', 'path'), name='regulation_asset_path_unique'),
        ),
    ]
