# Generated by Django 5.2.11 on 2026-06-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_provision_version_clauses_m2m_assets_drop_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationclause',
            name='target_division',
            field=models.CharField(blank=True, default='', help_text="Division the target provision lives in (e.g., 'Division B'). Empty for division-less editions (OBC 1997) or clauses with no single division (meta-amendments).", max_length=50),
        ),
    ]
