# Generated by Django 5.2.11 on 2026-06-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_regulationclause_target_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_label', models.CharField(default='Ontario Building Code', max_length=200)),
                ('corpus_span', models.CharField(blank=True, default='', max_length=50)),
                ('data_current_to', models.DateField(blank=True, null=True)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corpus Currency',
                'verbose_name_plural': 'Corpus Currency',
                'db_table': 'corpus_currency',
            },
        ),
        migrations.AlterField(
            model_name='regulationclause',
            name='target_division',
            field=models.CharField(blank=True, default='', help_text="Division the target provision lives in, as a bare letter ('A'/'B'/'C') matching CodeEditionProvision.division. Empty for division-less editions (OBC 1997) or clauses with no single division (meta-amendments).", max_length=50),
        ),
    ]
