# Generated by Django 5.2.11 on 2026-06-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_corpuscurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeeditionprovisionversion',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
