# Generated by Django 5.2.11 on 2026-06-02 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_corpuscurrency_coverage_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('provision_version_view', 'Provision version view'), ('regulation_view', 'Regulation view'), ('result_link_click', 'Result link click')], max_length=40)),
                ('object_type', models.CharField(blank=True, default='', max_length=50)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_events', to='core.searchhistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement Event',
                'verbose_name_plural': 'Engagement Events',
                'db_table': 'engagement_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='engagement__event_t_aca466_idx'), models.Index(fields=['object_type', 'object_id'], name='engagement__object__346bc9_idx'), models.Index(fields=['search'], name='engagement__search__4e19e3_idx')],
            },
        ),
    ]
