# Generated by Django 5.2.11 on 2026-06-02 11:07
#
# Provenance cleanup (tasks/provenance/5-cleanup.md): drop the legacy map
# stack (CodeMap, CodeMapNode), the eight superseded CodeEdition fields, and
# the KeywordIDF materialized view.
#
# Ordering note: the ``keyword_idf`` materialized view (migration 0011) is
# defined ``FROM code_map_nodes``, so Postgres refuses to drop that table
# while the view exists.  The DROP MATERIALIZED VIEW RunSQL therefore runs
# FIRST, before DeleteModel('CodeMapNode').  KeywordIDF is an unmanaged model,
# so its DeleteModel emits no DDL — the RunSQL is what actually removes the
# view.  On reverse, operations replay bottom-to-top: the tables are recreated
# before the view-recreate SQL runs, so the rollback path is valid too.

from django.db import migrations

RECREATE_MATVIEW = """
CREATE MATERIALIZED VIEW IF NOT EXISTS keyword_idf AS
SELECT
    cm.map_code,
    kw.key                                          AS keyword,
    COUNT(DISTINCT cmn.id)                          AS doc_count,
    (SELECT COUNT(*) FROM code_map_nodes cmn2
     WHERE cmn2.code_map_id = cm.id)                AS total_docs,
    LN((SELECT COUNT(*) FROM code_map_nodes cmn2
        WHERE cmn2.code_map_id = cm.id)::float
       / GREATEST(COUNT(DISTINCT cmn.id), 1)) + 1  AS idf
FROM code_maps cm
JOIN code_map_nodes cmn ON cmn.code_map_id = cm.id,
     LATERAL jsonb_each_text(cmn.keyword_counts) AS kw(key, value)
GROUP BY cm.id, cm.map_code, kw.key;

CREATE UNIQUE INDEX IF NOT EXISTS keyword_idf_lookup
    ON keyword_idf (map_code, keyword);
"""

DROP_MATVIEW = """
DROP MATERIALIZED VIEW IF EXISTS keyword_idf;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_engagementevent'),
    ]

    operations = [
        migrations.RunSQL(DROP_MATVIEW, RECREATE_MATVIEW),
        migrations.RemoveField(
            model_name='codemapnode',
            name='code_map',
        ),
        migrations.DeleteModel(
            name='KeywordIDF',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='amendments',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='amendments_applied',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='map_codes',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='pdf_files',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='codeedition',
            name='superseded_date',
        ),
        migrations.DeleteModel(
            name='CodeMap',
        ),
        migrations.DeleteModel(
            name='CodeMapNode',
        ),
    ]
