# Generated by Django 5.2.9 on 2026-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_codemapnode_code_map_delete_keywordidf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeeditionprovisionversion',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
