# Generated by Django 5.2.9 on 2026-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_codeeditionprovisionversion_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='commencement',
            field=models.JSONField(blank=True, help_text="CCM-parsed commencement records: the regulation's default 'comes into force on …' clause plus any staggered exceptions. Each record carries {clause, is_default, commencement_clause, effective_date, resolved_provisions, …}. The default record's date mirrors ``effective_date``; non-default records pin later in-force dates for the provisions they name.", null=True),
        ),
        migrations.AddField(
            model_name='regulationclause',
            name='add_anchor',
            field=models.TextField(blank=True, default='', help_text="Where ``add_text`` is inserted, e.g. 'after:CSA C22.2 No. 0.3, …'. The primary directive's anchor for a single-directive clause."),
        ),
        migrations.AddField(
            model_name='regulationclause',
            name='add_text',
            field=models.TextField(blank=True, default='', help_text="Text inserted by an 'amend by adding' directive, anchored at ``add_anchor``. Part of recording commencement at provision granularity: this is the content the clause brings into force on ``effective_date``."),
        ),
        migrations.AddField(
            model_name='regulationclause',
            name='directives',
            field=models.JSONField(blank=True, help_text="Full decomposition of a clause that amends several targets — the list of {action, target_level, target_id, target_division, strike_text, sub_text, add_text, add_anchor, …} directives. The flat target_*/strike_*/sub_*/add_* fields mirror the primary (first) directive; this list carries them all so the clause's ``effective_date`` (commencement) can be pinned onto every provision it touches, not just the primary target.", null=True),
        ),
        migrations.AddField(
            model_name='regulationclause',
            name='effective_date',
            field=models.DateField(blank=True, help_text="The clause's own commencement date — when this amending directive comes into force. Usually equal to the regulation's blanket effective_date, but Ontario regs routinely stagger commencement so a clause can come into force later (its date resolved by CCM from the regulation's commencement records).", null=True),
        ),
    ]
