# Generated by Django 5.2.9 on 2026-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_regulation_commencement_regulationclause_add_anchor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationclause',
            name='commencement',
            field=models.JSONField(blank=True, help_text="The single CommencementProvenance record that set this clause's ``effective_date`` — the *why* behind the date: the verbatim commencement subsection, its ``source`` (parsed / commencement-input / regulations-act-default / catalog), and for derived dates the ``depends_on`` statute and ``computation``. Resolved at load from the regulation's commencement schedule via ``resolved_clauses`` (with the default entry as fallback); see load_edition._resolve_clause_commencement. Mirrors one entry of ``Regulation.commencement``.", null=True),
        ),
    ]
