# Generated by Django 5.2.11 on 2026-06-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_regulationclause_commencement'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycache',
            name='date_is_relative',
            field=models.BooleanField(default=False),
        ),
    ]
