# Generated by Django 5.2.9 on 2026-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_querycache_date_is_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuscurrency',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
