# Generated by Django 5.2.11 on 2026-06-10 19:53

from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def seed_first_edition_dates(apps, schema_editor):
    """Stamp known real-world first-edition dates onto existing Code rows.

    ``load_edition`` also seeds these on every load (Code rows can be wiped
    and recreated); this just covers databases that won't reload soon.
    Keep in sync with ``load_edition.Command.FIRST_EDITION_DATES``.
    """
    Code = apps.get_model("core", "Code")
    Code.objects.filter(code="OBC").update(first_edition_date=date(1975, 12, 31))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_corpuscurrency_coverage_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='first_edition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EditionTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('new_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_back', to='core.codeedition')),
                ('old_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_forward', to='core.codeedition')),
            ],
            options={
                'verbose_name': 'Edition Transition',
                'verbose_name_plural': 'Edition Transitions',
                'db_table': 'edition_transitions',
                'constraints': [models.UniqueConstraint(fields=('old_edition', 'new_edition'), name='edition_transition_unique')],
            },
        ),
        migrations.RunPython(
            seed_first_edition_dates, migrations.RunPython.noop,
        ),
    ]
