# Generated by Django 5.2.11 on 2026-06-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_provision_lineage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discontinued', 'Discontinued'), ('not_processed', 'Not processed')], max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('new_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dispositions', to='core.codeedition')),
                ('provision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='core.codeeditionprovision')),
            ],
            options={
                'db_table': 'provision_dispositions',
                'constraints': [models.UniqueConstraint(fields=('provision', 'new_edition'), name='provision_disposition_unique')],
            },
        ),
    ]
