# Generated by Django 5.2.11 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_provision_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisiondisposition',
            name='target_reference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
