# Generated by Django 5.2.11 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_provisiondisposition_target_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeedition',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
