# Generated by Django 5.2.11 on 2026-06-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_codeedition_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='source_kind',
            field=models.CharField(blank=True, choices=[('elaws', 'e-Laws'), ('archive_gazette', 'Gazette (archive.org)'), ('ontario_ca', 'Ontario.ca'), ('other', 'Other')], default='', help_text='Which kind of source `source_url` points at, for labelling.', max_length=30),
        ),
        migrations.AddField(
            model_name='regulation',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Authoritative online location of the regulation as enacted (e.g. its e-Laws regulation page or an archive.org gazette scan). Supplied by CCM; absent → no source link is shown, never a guess.', max_length=500),
        ),
    ]
