# Generated by Django 5.2.11 on 2026-06-13 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_regulation_source_kind_regulation_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth Event',
                'verbose_name_plural': 'Auth Events',
                'db_table': 'auth_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='auth_events_event_t_a3d408_idx'), models.Index(fields=['ip_address', 'timestamp'], name='auth_events_ip_addr_80455a_idx'), models.Index(fields=['email', 'timestamp'], name='auth_events_email_a4755e_idx')],
            },
        ),
    ]
