# Generated by Django 5.2.11 on 2026-06-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_regulation_source_kind_regulation_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElawsConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('url', models.URLField(max_length=500)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaws_consolidations', to='core.codeedition')),
            ],
            options={
                'db_table': 'elaws_consolidations',
                'ordering': ['edition', 'version'],
                'indexes': [models.Index(fields=['edition', 'effective_from', 'effective_to'], name='elaws_consolidation_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('edition', 'version'), name='elaws_consolidation_edition_version_unique')],
            },
        ),
    ]
