# Generated by Django 5.2.11 on 2026-06-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_authevent'),
        ('core', '0036_elawsconsolidation'),
    ]

    operations = [
    ]
