# Generated by Django 5.2.11 on 2026-07-24 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_elawsconsolidation_consolidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_text', models.CharField(max_length=200)),
                ('occurrence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('container', models.CharField(choices=[('body', 'Body'), ('table', 'Table'), ('note', 'Table note')], default='body', max_length=10)),
                ('table_id', models.CharField(blank=True, default='', max_length=200)),
                ('start', models.PositiveIntegerField(blank=True, null=True)),
                ('end', models.PositiveIntegerField(blank=True, null=True)),
                ('targets', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='core.codeeditionprovisionversion')),
                ('to_provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cited_by', to='core.codeeditionprovision')),
            ],
            options={
                'db_table': 'provision_cross_references',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['to_provision'], name='provision_c_to_prov_fa1955_idx'), models.Index(fields=['from_version'], name='provision_c_from_ve_039244_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvisionCrossReferenceAlternate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cross_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternates', to='core.provisioncrossreference')),
                ('to_provision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cited_as_alternate', to='core.codeeditionprovision')),
            ],
            options={
                'db_table': 'provision_cross_reference_alternates',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['cross_reference'], name='provision_c_cross_r_579e3f_idx')],
            },
        ),
    ]
