# Generated by Django 5.2.11 on 2026-07-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_provisioncrossreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('provision_version_view', 'Provision version view'), ('regulation_view', 'Regulation view'), ('result_link_click', 'Result link click'), ('locked_content_view', 'Locked content view')], max_length=40),
        ),
    ]
