# Generated by Django 5.2.11 on 2026-07-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_engagement_locked_content_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='match_threshold',
            field=models.FloatField(default=0.8, help_text='Minimum relevance score for a result to count as a close match.'),
        ),
    ]
