# Generated by Django 5.2.11 on 2026-07-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_user_match_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeeditionprovisionversion',
            name='title_keyword_counts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
