# Generated by Django 5.2.11 on 2026-08-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_codeeditionprovisionversion_title_keyword_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('provision_version_view', 'Provision version view'), ('regulation_view', 'Regulation view'), ('result_link_click', 'Result link click'), ('locked_content_view', 'Locked content view'), ('rate_limit_block', 'Rate limit block')], max_length=40),
        ),
    ]
