# Generated by Django 5.2.11 on 2026-08-01 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_engagementevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('surface', models.CharField(choices=[('landing', 'Landing page'), ('rate_limit', 'Rate-limit teaser'), ('search', 'Search page')], default='landing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_requests', to='core.searchhistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edition_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edition Request',
                'verbose_name_plural': 'Edition Requests',
                'db_table': 'edition_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='edition_req_created_dccbc0_idx'), models.Index(fields=['surface', 'created_at'], name='edition_req_surface_020009_idx')],
            },
        ),
    ]
