# Generated by Django 5.2.11 on 2026-08-01 06:19
"""Split the clickwrap version stamp into Terms and Privacy.

Existing rows are backfilled with "2026-06-17" rather than left blank. That is
not a guess: the Privacy Policy carried "Last updated: June 17, 2026" from
then until 2026-08-01, so every acceptance recorded before this migration was
against exactly that text. Leaving the column blank would throw away a fact we
know, in the one table whose purpose is to record what a user agreed to.

Reversible, and the reverse only drops the column — no acceptance is deleted.
"""

from django.db import migrations, models

#: The Privacy Policy version in force for every pre-split acceptance.
PRE_SPLIT_PRIVACY_VERSION = "2026-06-17"


def backfill_privacy_version(apps, schema_editor):
    """Stamp pre-split rows with the Privacy Policy they actually accepted."""
    TermsAcceptance = apps.get_model("core", "TermsAcceptance")
    TermsAcceptance.objects.filter(privacy_version="").update(
        privacy_version=PRE_SPLIT_PRIVACY_VERSION
    )


def unset_privacy_version(apps, schema_editor):
    """Reverse: clear the backfill, leaving the rows as they were."""
    TermsAcceptance = apps.get_model("core", "TermsAcceptance")
    TermsAcceptance.objects.filter(
        privacy_version=PRE_SPLIT_PRIVACY_VERSION
    ).update(privacy_version="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_editionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsacceptance',
            name='privacy_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(backfill_privacy_version, unset_privacy_version),
        migrations.AddIndex(
            model_name='termsacceptance',
            index=models.Index(fields=['privacy_version'], name='terms_accep_privacy_81ed39_idx'),
        ),
    ]
