# Generated by Django 5.2.11 on 2026-08-02 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_termsacceptance_privacy_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_edition', models.CharField(max_length=50)),
                ('division', models.CharField(blank=True, default='', max_length=10)),
                ('provision_id', models.CharField(blank=True, default='', max_length=50)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('reg_id', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField()),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('surface', models.CharField(choices=[('permalink', 'Provision permalink'), ('search', 'Search result'), ('regulation', 'Regulation detail')], default='permalink', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('fixed', 'Fixed'), ('not_a_defect', 'Not a defect')], default='new', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provision_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provision Feedback',
                'verbose_name_plural': 'Provision Feedback',
                'db_table': 'provision_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='provision_f_created_ba3477_idx'), models.Index(fields=['status', 'created_at'], name='provision_f_status_983935_idx'), models.Index(fields=['code_edition', 'provision_id'], name='provision_f_code_ed_abbafd_idx')],
            },
        ),
    ]
