# Generated by Django 5.2.11 on 2026-08-02 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_provisionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionVersionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('original_url', models.CharField(blank=True, default='', max_length=500)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.codeeditionprovisionversion')),
            ],
            options={
                'db_table': 'provision_version_assets',
                'indexes': [models.Index(fields=['path'], name='provision_v_path_22c441_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'path'), name='provision_version_asset_path_unique')],
            },
        ),
    ]
