# Generated by Django 5.2.11 on 2026-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_engagementevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('provision_version_view', 'Provision version view'), ('regulation_view', 'Regulation view'), ('result_link_click', 'Result link click'), ('locked_content_view', 'Locked content view'), ('version_comparison', 'Version comparison'), ('rate_limit_block', 'Rate limit block'), ('export', 'Export')], max_length=40),
        ),
    ]
