# Generated by Django 5.2.11 on 2026-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_engagementevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionrequest',
            name='notified_about',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='editionrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
