# Generated by Django 5.2.11 on 2026-08-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_editionrequest_notified_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('upload', 'Uploaded off-host'), ('local', 'Local drill')], default='upload', max_length=10)),
                ('succeeded', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True, default='')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Backup Run',
                'verbose_name_plural': 'Backup Runs',
                'db_table': 'backup_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['kind', 'succeeded', '-started_at'], name='backup_runs_kind_462eb2_idx')],
            },
        ),
    ]
