# Generated by Django 5.2.11 on 2026-08-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('api', 'Direct API')], db_index=True, default='web', max_length=8),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'source', 'timestamp'], name='search_hist_user_id_8e04b2_idx'),
        ),
    ]
