# Generated by Django 5.2.11 on 2026-08-18 08:08
#
# Hand-edited afterwards, before release: ``source`` and the per-surface index
# were folded in here rather than added by a follow-up migration.  ``source``
# carries no default on the model, so a follow-up would have needed a one-off
# fill value for rows that do not exist anywhere — this table had never been
# created outside a developer's own machine.  Safe only because this migration
# was unreleased; do not edit it again.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_searchhistory_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_edition', models.CharField(max_length=50)),
                ('division', models.CharField(blank=True, default='', max_length=10)),
                ('provision_id', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('source', models.CharField(choices=[('web', 'Website'), ('api', 'Direct API')], db_index=True, max_length=8)),
                ('fetch_count', models.PositiveIntegerField(default=1)),
                ('first_fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provision_fetches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provision Fetch',
                'verbose_name_plural': 'Provision Fetches',
                'db_table': 'provision_fetches',
                'ordering': ['-last_fetched_at'],
                'indexes': [models.Index(fields=['user', 'first_fetched_at'], name='provision_f_user_id_022504_idx'), models.Index(fields=['user', 'last_fetched_at'], name='provision_f_user_id_7a8f50_idx'), models.Index(fields=['user', 'source', 'first_fetched_at'], name='provision_f_user_id_d89e68_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code_edition', 'division', 'provision_id', 'version'), name='unique_provision_fetch_per_user'), models.CheckConstraint(condition=models.Q(('source__in', ['web', 'api'])), name='provision_fetch_names_its_surface')],
            },
        ),
    ]
