# Generated by Django 5.2.11 on 2026-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_subscriber_is_the_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementevent',
            name='event_type',
            field=models.CharField(choices=[('provision_version_view', 'Provision version view'), ('regulation_view', 'Regulation view'), ('result_link_click', 'Result link click'), ('locked_content_view', 'Locked content view'), ('version_comparison', 'Version comparison'), ('rate_limit_block', 'Rate limit block'), ('export', 'Export'), ('api_throttle', 'API throttle')], max_length=40),
        ),
    ]
